# This file was generated by swiftpm2nix.
{
  workspaceStateFile = ./workspace-state.json;
  hashes = {
    "swift-argument-parser" = "0fk028s2gcq1cbsl2056qbp359yk8p249f2pss4zc23hk756sgkw";
    "swifter" = "0gfyqsl4crgpzn5xs5kyszmpj81ds567v7ch0i1gm59zpp5kw1vi";
    "SwiftIP" = "05vyc46hpc1jbsg15v39qfm5r3gyrlszk2nybvygax6jznlzqs1a";
  };
}
